[project]
name = "blueOcean"
version = "0.1.0"
dependencies = [
    "pandas",
    "scikit-learn",
    "plotly",
    "numpy",
    "backtrader",
    "logging",
    "python-dotenv",
    "influxdb-client",
]
